name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./public
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public
          branch: gh-pages
          clean-exclude: pr-preview
          force: false

  dispatch-gh-page-deploy:
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dispatch workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run "deploy-gh-page.yml"
